In [3]:
import torch

model = torch.load('cbow.pth', weights_only=False)
model

OrderedDict([('linear1.weight',
              tensor([[ 1.3356,  2.0179,  0.6696,  ...,  2.7504,  2.3757,  1.4298],
                      [ 1.1445,  2.1191,  1.7123,  ..., -0.8261, -0.3514, -0.4124],
                      [-1.0139, -2.5298, -2.4429,  ...,  1.3998,  1.4179, -0.1805],
                      [ 0.1485,  0.4465,  1.0431,  ...,  0.7520,  0.6596,  0.4087],
                      [ 0.3828,  1.3517,  2.2198,  ..., -1.8544, -1.9071, -0.7468]])),
             ('linear2.weight',
              tensor([[ 0.0063,  0.1954,  0.0195,  0.2265, -0.0124],
                      [-0.3043, -0.2069, -0.2456, -0.2312,  0.0446],
                      [ 3.0063,  2.4371, -3.0272,  0.4734,  3.0188],
                      ...,
                      [ 4.7883, -1.1781,  1.1324,  0.7263, -2.5136],
                      [-0.0838,  0.1339,  0.2105,  0.2763, -0.0434],
                      [ 0.1922, -0.2368,  0.1076, -0.0787,  0.1972]])),
             ('linear2.bias',
              tensor([-0.4940, -0.6440,

In [16]:
embeddings = model['linear1.weight']
embeddings = embeddings.transpose(0, 1)
embeddings

tensor([[ 1.3356,  1.1445, -1.0139,  0.1485,  0.3828],
        [ 2.0179,  2.1191, -2.5298,  0.4465,  1.3517],
        [ 0.6696,  1.7123, -2.4429,  1.0431,  2.2198],
        ...,
        [ 2.7504, -0.8261,  1.3998,  0.7520, -1.8544],
        [ 2.3757, -0.3514,  1.4179,  0.6596, -1.9071],
        [ 1.4298, -0.4124, -0.1805,  0.4087, -0.7468]])

In [11]:
import pickle

with open('word2ind_map.pkl', 'rb') as file:
    word2ind = pickle.load(file)
with open('ind2word_map.pkl', 'rb') as file:
    ind2word = pickle.load(file)

In [17]:
def get_word_embedding(word):
    word_ind = word2ind[word]
    return embeddings[word_ind]

In [19]:
def cosine_similarity(word1, word2):
    vector1 = get_word_embedding(word1)
    vector2 = get_word_embedding(word2)
    return torch.dot(vector1, vector2) / (torch.norm(vector1) * torch.norm(vector2))

In [18]:
word1 = "beautiful"
embedding1 = get_word_embedding(word1)

In [34]:
word2 = "ugly"
embedding2 = get_word_embedding(word2)

In [35]:
print(cosine_similarity(word1, word2))

tensor(-0.3306)
